/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AlbsButton {
        "disabled": boolean;
        "loading": boolean;
        "type": 'submit' | 'reset' | 'button';
    }
}
declare global {
    interface HTMLAlbsButtonElement extends Components.AlbsButton, HTMLStencilElement {
    }
    var HTMLAlbsButtonElement: {
        prototype: HTMLAlbsButtonElement;
        new (): HTMLAlbsButtonElement;
    };
    interface HTMLElementTagNameMap {
        "albs-button": HTMLAlbsButtonElement;
    }
}
declare namespace LocalJSX {
    interface AlbsButton {
        "disabled"?: boolean;
        "loading"?: boolean;
        "onClickEmitter"?: (event: CustomEvent<any>) => void;
        "type"?: 'submit' | 'reset' | 'button';
    }
    interface IntrinsicElements {
        "albs-button": AlbsButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "albs-button": LocalJSX.AlbsButton & JSXBase.HTMLAttributes<HTMLAlbsButtonElement>;
        }
    }
}
