/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { InputChangeEventDetail } from "./components/input/types";
export namespace Components {
    interface AlbsButton {
        "disabled": boolean;
        "loading": boolean;
        "type": 'submit' | 'reset' | 'button';
    }
    interface AlbsInput {
        "disabled"?: boolean;
        "inputmode"?: 'none' | 'text' | 'decimal' | 'numeric' | 'tel' | 'search' | 'email' | 'url';
        "placeholder": string;
        "required"?: boolean;
        "type": 'date' | 'datetime-local' | 'email' | 'month' | 'number' | 'password' | 'search' | 'tel' | 'text' | 'time' | 'url' | 'week' | 'datetime';
        "value"?: string | number | null;
    }
}
declare global {
    interface HTMLAlbsButtonElement extends Components.AlbsButton, HTMLStencilElement {
    }
    var HTMLAlbsButtonElement: {
        prototype: HTMLAlbsButtonElement;
        new (): HTMLAlbsButtonElement;
    };
    interface HTMLAlbsInputElement extends Components.AlbsInput, HTMLStencilElement {
    }
    var HTMLAlbsInputElement: {
        prototype: HTMLAlbsInputElement;
        new (): HTMLAlbsInputElement;
    };
    interface HTMLElementTagNameMap {
        "albs-button": HTMLAlbsButtonElement;
        "albs-input": HTMLAlbsInputElement;
    }
}
declare namespace LocalJSX {
    interface AlbsButton {
        "disabled"?: boolean;
        "loading"?: boolean;
        "onClickEmitter"?: (event: CustomEvent<any>) => void;
        "type"?: 'submit' | 'reset' | 'button';
    }
    interface AlbsInput {
        "disabled"?: boolean;
        "inputmode"?: 'none' | 'text' | 'decimal' | 'numeric' | 'tel' | 'search' | 'email' | 'url';
        "onChangeEmitter"?: (event: CustomEvent<any>) => void;
        "onInputChangeEmitter"?: (event: CustomEvent<InputChangeEventDetail>) => void;
        "onInputEmitter"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "required"?: boolean;
        "type"?: 'date' | 'datetime-local' | 'email' | 'month' | 'number' | 'password' | 'search' | 'tel' | 'text' | 'time' | 'url' | 'week' | 'datetime';
        "value"?: string | number | null;
    }
    interface IntrinsicElements {
        "albs-button": AlbsButton;
        "albs-input": AlbsInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "albs-button": LocalJSX.AlbsButton & JSXBase.HTMLAttributes<HTMLAlbsButtonElement>;
            "albs-input": LocalJSX.AlbsInput & JSXBase.HTMLAttributes<HTMLAlbsInputElement>;
        }
    }
}
